### ISSUE TITLE
大佬你这个里面COLORCNN输出的color_palette 可以看作是提取出的能代表原图像主要颜色的调色板吗？

### ISSUE THREAD

**Issue by Viktorjc98** [hou-yz/color_distillation#1]
大佬你这个里面COLORCNN输出的color_palette 可以看作是提取出的能代表原图像主要颜色的调色板吗？为什么我把它乘255之后保存，里面的颜色跟原图以及重建的图像里的颜色感觉毫不相干呢？求大佬解惑？谢谢！我就是想做一个能提取图像调色板的深度学习模型，可以参考你这个吗？

**Comment by hou-yz** [comment]
thank you for your interest. 

yes, you can think of the color palette as representative colors for the image. please see [code](https://github.com/hou-yz/color_distillation/blob/4293206d1deb10540920e284159d430e041f5a50/color_distillation/models/color_cnn.py#L34) on how to reconstruct the RGB image using the color palette and the index map. 

since this work only optimizes for neural network recognition accuracy, the color quantization results might not be the most visually accurate. for improved visual fidelity, please see our improved version, ColorCNN+, at this [link](https://github.com/hou-yz/color_distillation_clustering).

![image](https://github.com/hou-yz/color_distillation/assets/24713675/b9acd0b6-0087-4546-b57d-4d0433d19347)


you are more than welcome to use this model as a baseline for your deep learning model on extracting color palette. 

best,
Yunzhong

**Comment by Viktorjc98** [comment]
> thank you for your interest.
> 
> yes, you can think of the color palette as representative colors for the image. please see [code](https://github.com/hou-yz/color_distillation/blob/4293206d1deb10540920e284159d430e041f5a50/color_distillation/models/color_cnn.py#L34) on how to reconstruct the RGB image using the color palette and the index map.
> 
> since this work only optimizes for neural network recognition accuracy, the color quantization results might not be the most visually accurate. for improved visual fidelity, please see our improved version, ColorCNN+, at this [link](https://github.com/hou-yz/color_distillation_clustering).
> 
> ![image](https://user-images.githubusercontent.com/24713675/261627045-b9acd0b6-0087-4546-b57d-4d0433d19347.png)
> 
> you are more than welcome to use this model as a baseline for your deep learning model on extracting color palette.
> 
> best, Yunzhong

好的，我试一下，谢谢大佬！

**Comment by Viktorjc98** [comment]
对了，我还有个问题就是，是直接将color_palette *255，就可以得到真实可视化的调色板吗？还是需要其他操作呢？

**Comment by Viktorjc98** [comment]
大佬放假了吗？/(ㄒoㄒ)/~~ @hou-yz

**Comment by hou-yz** [comment]
> 对了，我还有个问题就是，是直接将color_palette *255，就可以得到真实可视化的调色板吗？还是需要其他操作呢？

可以
